INSERT INTO `data_premission` VALUES (1, '商品管理', 0, '0', '', '');
INSERT INTO `data_premission` VALUES (2, '用户管理', 0, '0', '', '');
INSERT INTO `data_premission` VALUES (3, '权限管理', 0, '0', '', '');
INSERT INTO `data_premission` VALUES (4, '订单管理', 0, '0', '', '');
INSERT INTO `data_premission` VALUES (5, '数据统计', 0, '0', '', '');
INSERT INTO `data_premission` VALUES (6, '用户列表', 2, '1', '', '');
INSERT INTO `data_premission` VALUES (7, '角色列表', 3, '1', '', '');
INSERT INTO `data_premission` VALUES (8, '权限列表', 3, '1', '', '');
INSERT INTO `data_premission` VALUES (9, '添加用户', 6, '2', '', '');
INSERT INTO `data_premission` VALUES (10, '删除用户', 6, '2', '', '');
INSERT INTO `data_premission` VALUES (11, '更新用户', 6, '2', '', '');
INSERT INTO `data_premission` VALUES (12, '获取用户详情', 6, '2', '', '');
INSERT INTO `data_premission` VALUES (13, '添加角色', 7, '2', ' ', ' ');
INSERT INTO `data_premission` VALUES (14, '删除角色', 7, '2', ' ', ' ');
INSERT INTO `data_premission` VALUES (15, '获取角色列表', 7, '2', ' ', ' ');
INSERT INTO `data_premission` VALUES (16, '获取角色详情', 7, '2', ' ', ' ');
INSERT INTO `data_premission` VALUES (17, '更新角色信息', 7, '2', ' ', ' ');
INSERT INTO `data_premission` VALUES (18, '更新角色权限', 7, '2', ' ', ' ');
INSERT INTO `data_premission` VALUES (19, '分配用户角色', 6, '2', ' ', ' ');
