INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (1, ' ', NULL, 1, 'goods');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (2, ' ', NULL, 2, 'users');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (3, ' ', NULL, 3, 'rights');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (4, ' ', NULL, 4, 'orders');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (5, 'getAllRights', NULL, 8, 'rights');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (6, ' ', NULL, 5, 'reports');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (7, 'getAllUsers', NULL, 6, 'users');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (8, 'createUser', NULL, 9, 'users');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (9, 'deleteUser', NULL, 10, 'users');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (10, 'updateUser', NULL, 11, 'users');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (11, 'getUser', NULL, 12, 'users');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (12, 'getAllRoles', NULL, 7, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (13, 'createRole', NULL, 13, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (14, 'deleteRole', NULL, 14, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (15, 'updateRole', NULL, 17, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (16, 'getRoleById', NULL, 16, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (17, 'updateRoleRight', NULL, 18, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (18, 'setRole', NULL, 19, 'roles');
INSERT INTO `data_premission_api` (`id`, `ps_api_action`, `ps_api_order`, `ps_id_id`, `ps_api_path`) VALUES (19, 'getAllRoles', NULL, 15, 'roles');
