INSERT INTO `data_premission_api` VALUES (1, ' ', NULL, 1, 'goods');
INSERT INTO `data_premission_api` VALUES (2, ' ', NULL, 2, 'users');
INSERT INTO `data_premission_api` VALUES (3, ' ', NULL, 3, 'rights');
INSERT INTO `data_premission_api` VALUES (4, ' ', NULL, 4, 'orders');
INSERT INTO `data_premission_api` VALUES (5, 'get_premission_list', NULL, 8, 'rights');
INSERT INTO `data_premission_api` VALUES (6, ' ', NULL, 5, 'reports');
INSERT INTO `data_premission_api` VALUES (7, 'getAllUsers', NULL, 6, 'users');
INSERT INTO `data_premission_api` VALUES (8, 'createUser', NULL, 9, 'users');
INSERT INTO `data_premission_api` VALUES (9, 'deleteUser', NULL, 10, 'users');
INSERT INTO `data_premission_api` VALUES (10, 'updateUser', NULL, 11, 'users');
INSERT INTO `data_premission_api` VALUES (11, 'getUser', NULL, 12, 'users');
INSERT INTO `data_premission_api` VALUES (12, 'getAllRoles', NULL, 7, 'roles');
INSERT INTO `data_premission_api` VALUES (13, 'createRole', NULL, 13, 'roles');
INSERT INTO `data_premission_api` VALUES (14, 'deleteRole', NULL, 14, 'roles');
INSERT INTO `data_premission_api` VALUES (15, 'updateRole', NULL, 17, 'roles');
INSERT INTO `data_premission_api` VALUES (16, 'getRoleById', NULL, 16, 'roles');
INSERT INTO `data_premission_api` VALUES (17, 'updateRoleRight', NULL, 18, 'roles');
INSERT INTO `data_premission_api` VALUES (18, 'setRole', NULL, 19, 'roles');
INSERT INTO `data_premission_api` VALUES (19, 'getAllRoles', NULL, 15, 'roles');
