INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (1, '商品管理', 0, '0', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (2, '用户管理', 0, '0', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (3, '权限管理', 0, '0', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (4, '订单管理', 0, '0', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (5, '数据统计', 0, '0', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (6, '用户列表', 2, '1', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (7, '角色列表', 3, '1', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (8, '权限列表', 3, '1', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (9, '添加用户', 6, '2', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (10, '删除用户', 6, '2', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (11, '更新用户', 6, '2', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (12, '获取用户详情', 6, '2', '', '');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (13, '添加角色', 7, '2', ' ', ' ');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (14, '删除角色', 7, '2', ' ', ' ');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (15, '获取角色列表', 7, '2', ' ', ' ');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (16, '获取角色详情', 7, '2', ' ', ' ');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (17, '更新角色信息', 7, '2', ' ', ' ');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (18, '更新角色权限', 7, '2', ' ', ' ');
INSERT INTO `data_premission` (`id`, `ps_name`, `ps_pid`, `ps_level`, `ps_c`, `ps_d`) VALUES (19, '分配用户角色', 6, '2', ' ', ' ');
